### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by jjxjiaxue** [zjutcvg/DiffCalib#1]
thank you for your remarkable work. could you please share your open source plan, like a checklist? thank you so much.
i would be very grateful if you can share your code asap

**Comment by shuiyued** [comment]
Thank you for your interest in our work. We will be releasing our inference code and checklist in the middle of this month. If all goes well, we will release the training code soon after.

**Comment by jjxjiaxue** [comment]
thank you so much!

**Comment by runnerhdh** [comment]
Looking forward to it too!
