### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thibble** [zjutcvg/DiffCalib#3]
Hey, thanks again for publishing this!

Which License are the models released under?

**Comment by shuiyued** [comment]
Hello, we have updated the License. Thanks for your interest.

**Comment by thibble** [comment]
@shuiyued The Readme says it's for non-commercial use.

What is the license for commercial use?

**Comment by shuiyued** [comment]
Hello, 
for any commercial use please email the corresponding author guodongyan@zjut.edu.cn.
