### ISSUE TITLE
Is it possible to upload the ckpts to other cloud servers?

### ISSUE THREAD

**Issue by JunyuanDeng** [zjutcvg/DiffCalib#4]
We found it's hard to download file from Baidu Disk, could you upload relevent file to other cloud like goolge cloud disk?

**Comment by shuiyued** [comment]
which checkpoint do you want for the Google Cloud disk?
We found that only one checkpoint could be uploaded because of the limited space of 15GB.

**Comment by JunyuanDeng** [comment]
Hi, I want the ckpt that can predict the camera intrinsic, thanks in advance!

**Comment by shuiyued** [comment]
I know, I am sorry for the late response, the link is pasted below.
https://drive.google.com/file/d/1Jyes3ZT5MCMhsxtd7exF-PTyYXiw9LF2/view?usp=sharing
